In [12]:
from numpy import *
import matplotlib.pyplot as plt

from numpy import random
import numpy as np


### 1. Create a 4x4 matrix with values ranging from 0 to 15

In [28]:
A = array([[n+m*4 for n in range(4)] for m in range(4)])

A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

### 2. Find indices of non-zero elements from [1,2,0,0,4,0,5,7,8,0,0,0]

In [14]:
v = array([1,2,0,0,4,0,5,7,8,0,0,0])  

# for element in v:
#     if element != 0:
#         print(element)


#x = v[where(v != 0)]
#x, v
v[v!=0]

array([1, 2, 4, 5, 7, 8])

### 3. Create a 3x3 identity matrix

In [56]:
A = array([[1*1 for n in range(3)] for m in range(3)])

A

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

### 4. Create a 10x10 array with random values and find the minimum and maximum values

In [48]:
m = random.rand(10,10)
max = m.max()
min = m.min()
print(max)
print(min)

### 5. Create a random vector of size 30 and find the mean value

In [35]:
z = random.random(30)
m = z.mean()
print(z)
print(m)

[ 0.9469602   0.46259782  0.67717099  0.00968237  0.09641428  0.02921101
  0.73528183  0.15478439  0.59905828  0.64328856  0.93206749  0.56526342
  0.91729384  0.57725304  0.58700786  0.12019091  0.7374597   0.66837604
  0.39444981  0.90434999  0.6749061   0.95116643  0.45728216  0.58691252
  0.6751615   0.82526901  0.95967436  0.66549348  0.95720872  0.31734181]
0.594285931059


### 6. Create a 2d array with 1 on the border and 0 inside

In [41]:
k = ones((10,10))
k[1:-1,1:-1] = 0
print(k)

[[ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]]


### 7. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [44]:
e = diag(1+arange(4),k=-1)
print(e)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


### 8. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) 

In [53]:
s = dot(ones((5,3)), ones((3,2)))
print(s)

# Alternative solution, in Python 3.5 and above
s = ones((5,3)) @ ones((3,2))
print(s)

[[ 3.  3.]
 [ 3.  3.]
 [ 3.  3.]
 [ 3.  3.]
 [ 3.  3.]]
[[ 3.  3.]
 [ 3.  3.]
 [ 3.  3.]
 [ 3.  3.]
 [ 3.  3.]]


### 9. How to find common values between two arrays?

In [64]:
a = random.randint(0,10,10)
b = random.randint(0,10,10)
print(intersect1d(a,b))

[2 4 6 9]


### 10. Create a random vector of size 10 and sort it

In [65]:
e = random.random(10)
e.sort()
print(Z)

[ 0.18052968  0.22318079  0.30292504  0.50640307  0.5735271   0.65991916
  0.76490958  0.79147998  0.82947335  0.9040679 ]


### 11. Create random vector of size 10 and replace the maximum value by 0

In [66]:
a = random.random(10)
a[a.argmax()] = 0
print(a)

[ 0.06571174  0.          0.63517811  0.03723149  0.260327    0.62695865
  0.23220699  0.25471123  0.32261883  0.40308281]


### 12. How to find the closest value (to a given scalar) in a vector?

In [69]:
a = arange(100)
b = random.uniform(0,100)
index = (abs(a-b)).argmin()
print(a[index])

35


### 13. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? 

In [77]:
a = array([1,2,3,4,5])
e = 3
b = zeros(len(a) + (len(a)-1)*(e))
b[::e+1] = a
print(b)


[ 1.  0.  0.  0.  2.  0.  0.  0.  3.  0.  0.  0.  4.  0.  0.  0.  5.]


### 14. How to swap two rows of a matrix?

In [78]:
A = arange(25).reshape(5,5)
A[[0,1]] = A[[1,0]]
print(A)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


### 15. How to find the most frequent value in an array?

In [82]:
r = random.randint(1,10,50)
print(bincount(r).argmax())

4


### 16. How to get the n largest values of an array?

In [87]:
a = arange(10000)
random.shuffle(a)
n = 5

# Slow
print (a[argsort(a)[-n:]])

# Fast
print (a[argpartition(-a,n)[:n]])

[9995 9996 9997 9998 9999]
[9997 9998 9996 9995 9999]
